--liquibase formatted sql
--changeset andrew.siquieri:1.0.1 endDelimiter:\

do $$
DECLARE
  counted integer;
BEGIN

  SELECT COUNT(table_name) INTO counted FROM information_schema.tables WHERE table_name = 'ROLE';
  IF counted = 0 THEN
    EXECUTE 'CREATE TABLE ROLE (
      ID   SERIAL       NOT NULL PRIMARY KEY,
      NAME VARCHAR(255) NOT NULL)';
  END IF;

  SELECT COUNT(table_name) INTO counted FROM information_schema.tables WHERE table_name = 'PRIVILEGE';
  IF counted = 0 THEN
    EXECUTE 'CREATE TABLE PRIVILEGE (
      ID   SERIAL       NOT NULL PRIMARY KEY,
      NAME VARCHAR(255) NOT NULL)';
  END IF;

  SELECT COUNT(table_name) INTO counted FROM information_schema.tables WHERE table_name = 'USER_ROLES';
  IF counted = 0 THEN
    EXECUTE 'CREATE TABLE USER_ROLES (
      USER_ID INTEGER NOT NULL REFERENCES USER_INFO(ID) ON UPDATE CASCADE ON DELETE CASCADE,
      ROLE_ID INTEGER NOT NULL REFERENCES ROLE(ID) ON UPDATE CASCADE ON DELETE CASCADE,
      CONSTRAINT USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID))';
  END IF;

  SELECT COUNT(table_name) INTO counted FROM information_schema.tables WHERE table_name = 'ROLE_PRIVILEGES';
  IF counted = 0 THEN
    EXECUTE 'CREATE TABLE ROLE_PRIVILEGES (
      ROLE_ID      INTEGER NOT NULL REFERENCES ROLE(ID) ON UPDATE CASCADE ON DELETE CASCADE,
      PRIVILEGE_ID INTEGER NOT NULL REFERENCES PRIVILEGE(ID) ON UPDATE CASCADE ON DELETE CASCADE,
      CONSTRAINT ROLE_PRIVILEGES_PK PRIMARY KEY (ROLE_ID, PRIVILEGE_ID))';
  END IF;

  EXECUTE 'INSERT INTO PRIVILEGE (NAME) VALUES (''READ_PRIVILEGE''), (''WRITE_PRIVILEGE''), (''DELETE_PRIVILEGE'')';
  EXECUTE 'INSERT INTO ROLE (NAME) VALUES (''ADMIN''), (''STAFF''), (''USER'')';
  EXECUTE 'INSERT INTO USER_INFO (EMAIL, PASSWORD, USER_NAME) VALUES
           (''admin@email.com'', MD5(''admin''), ''admin''),
           (''staff@email.com'', MD5(''staff''), ''staff''),
           (''user@email.com'', MD5(''user''), ''user'')';

  EXECUTE 'INSERT INTO ROLE_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES
           ((SELECT ID FROM ROLE WHERE NAME = ''USER''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''READ_PRIVILEGE'')),
           ((SELECT ID FROM ROLE WHERE NAME = ''STAFF''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''READ_PRIVILEGE'')),
           ((SELECT ID FROM ROLE WHERE NAME = ''STAFF''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''WRITE_PRIVILEGE'')),
           ((SELECT ID FROM ROLE WHERE NAME = ''ADMIN''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''READ_PRIVILEGE'')),
           ((SELECT ID FROM ROLE WHERE NAME = ''ADMIN''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''WRITE_PRIVILEGE'')),
           ((SELECT ID FROM ROLE WHERE NAME = ''ADMIN''), (SELECT ID FROM PRIVILEGE WHERE NAME = ''DELETE_PRIVILEGE''))';

  EXECUTE 'INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES
           ((SELECT ID FROM USER_INFO WHERE USER_NAME = ''admin''), (SELECT ID FROM ROLE WHERE NAME = ''ADMIN'')),
           ((SELECT ID FROM USER_INFO WHERE USER_NAME = ''staff''), (SELECT ID FROM ROLE WHERE NAME = ''STAFF'')),
           ((SELECT ID FROM USER_INFO WHERE USER_NAME = ''user''), (SELECT ID FROM ROLE WHERE NAME = ''USER''))';

END $$
\
