name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - feature/complete-java
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Configuring Maven permission
        run: chmod +x mvnw

      - name: Maven Test
        run: ./mvnw test
